config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants, only: [:new, :index, :create, :show] do
    resources :reviews, only: [ :new, :create ]
    collection do

    end

    member do

    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  CATEGORIES = ["chinese", "italian", "japanese", "french", "belgian"]
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  # validates :category, inclusion: {in: CATEGORIES}
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :rating, inclusion: {in: [0,1,2,3,4,5]}, :numericality => {:only_integer => true}
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :find_restaurant, only: [:show]
  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    Restaurant.create(restaurant_params)
    redirect_to "/restaurants"
  end

  private
  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end

  def find_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    find_restaurant
    @review = Review.new
  end

  def create
    find_restaurant
    @restaurant.reviews.create(review_params)
    redirect_to "/restaurants/#{@restaurant.id}"
  end

  private
  def review_params
    params.require(:review).permit(:content, :rating, :restaurant_id)
  end

  def find_review
    @review = Review.find([:id])
  end
  def find_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurant_helper.rb
module RestaurantHelper
    def display_stars(rating)
    "☆" * rating
    end
end

app/helpers/review_helper.rb
module ReviewHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <link rel="stylesheet" href="/assets/stylesheet/application.css">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="nav">
    <ul class="navbar">
  <li class="list-navbar"><a class="active" href="/restaurants">Home</a></li>
  <li class="list-navbar"><a href="#about">About</a></li>
</ul>
</div>
    <div class="wrapper">
    <%= yield %>
    </div>
  </body>
</html>

app/views/restaurants/index.html.erb
<h2>Restaurant List</h2>
<ul class="restaurants-list">
  <% @restaurants.each do |r| %>
  <li class="restaurant-each text-center"><%= r.name %> |
    <%= r.category.capitalize %> <br>
    <%= link_to "More details", restaurant_path(id: r.id) %>
  </li>
  <% end %>
</ul>
  <%= link_to "Add a new Restaurant", new_restaurant_path, class: "new-restaurant"  %>

app/views/restaurants/new.html.erb
<div class="new-restaurant-container">
<h2>New Restaurant</h2>
<%= form_for(@restaurant) do |f| %>
<div class="text-center">
  <%= f.label :name %><br>
  <%= f.text_field :name %>
</div>
<div class="text-center">
  <%= f.label :address %><br>
  <%= f.text_field :address %>
</div>

  <div class="text-center">
  <%= f.label :phone_number %><br>
  <%= f.text_field :phone_number %>
</div>
<div>
<br>
  <%= f.select :category,  Restaurant::CATEGORIES, {include_blank: 'Category'} %>
  <%= f.submit class: "submit-btn" %>
</div>
<% end %>
</div>

app/views/restaurants/show.html.erb
<h2><%= @restaurant.name %> | <%= @restaurant.category %></h2>
<h3><%= @restaurant.address %></h3>
<h4><%=  @restaurant.phone_number %></h4>

<% @restaurant.reviews.each do |r| %>
<p><%= r.content %> <%= display_stars(r.rating) %></p>
<% end %>

<%= link_to "Add a review", new_restaurant_review_path(@restaurant.id)  %>
<%= link_to "Return to restaurant list", restaurants_path  %>

app/views/reviews/new.html.erb
<div class="new-review">
<h2>New review for <strong><%= @restaurant.name %></strong></h2>

<%= form_for([@restaurant, @review]) do |f| %>
<div class="text-center">
  <%= f.label :content %><br>
  <%= f.text_area :content %>
</div>
<div class="text-center">
  <%= f.select :rating, [0,1,2,3,4,5], {include_blank: 'Rating'} %>
  <%= f.submit class: "submit-btn"%>
</div>
<% end %>
</div>